from pydantic import BaseModel, Field
from agents import Agent

# --- Instructions for the Agent ---

# Define the system instructions for the writer agent.
# These instructions set the persona of a senior researcher and outline the task:
# to create a comprehensive, well-structured report based on a query and initial research.
INSTRUCTIONS = (
    "You are a senior researcher tasked with writing a cohesive report for a research query. "
    "You will be provided with the original query, and some initial research done by a research assistant.\n"
    "You should first come up with an outline for the report that describes the structure and "
    "flow of the report. Then, generate the report and return that as your final output.\n"
    "The final output should be in markdown format, and it should be lengthy and detailed. Aim "
    "for 5-10 pages of content, at least 1000 words."
)

# --- Pydantic Output Schema ---

class ReportData(BaseModel):
    """
    Defines the structure of the output generated by the writer agent.
    This ensures the final report is well-organized and contains all required components.
    """
    # A concise summary of the key findings in the report.
    short_summary: str = Field(description="A short 2-3 sentence summary of the findings.")
    
    # The main body of the report in Markdown format.
    markdown_report: str = Field(description="The final report")
    
    # A list of suggested follow-up questions or research topics.
    follow_up_questions: list[str] = Field(description="Suggested topics to research further")

# --- Agent Definition ---

# Create an instance of the `Agent` class to define the writer agent.
writer_agent = Agent(
    name="WriterAgent",
    instructions=INSTRUCTIONS,
    model="gpt-4o-mini",
    # The `output_type` is set to `ReportData`, instructing the agent to structure
    # its final output according to this Pydantic model.
    output_type=ReportData,
)