#!/usr/bin/env python
import sys
import warnings
import os
from datetime import datetime

from engineering_team.crew import EngineeringTeam

# Suppress SyntaxWarning from the `pysbd` module, which is a known issue.
# This helps to keep the output clean and focused on the application's logic.
warnings.filterwarnings("ignore", category=SyntaxWarning, module="pysbd")

# --- Configuration ---
# Create the 'output' directory if it doesn't already exist.
# This directory is used to store the results and artifacts generated by the crew.
os.makedirs('output', exist_ok=True)

# Define the high-level requirements for the system to be built.
# This multi-line string serves as the primary input for the engineering team,
# outlining the features and constraints of the account management system.
requirements = """
A simple account management system for a trading simulation platform.
The system should allow users to create an account, deposit funds, and withdraw funds.
The system should allow users to record that they have bought or sold shares, providing a quantity.
The system should calculate the total value of the user's portfolio, and the profit or loss from the initial deposit.
The system should be able to report the holdings of the user at any point in time.
The system should be able to report the profit or loss of the user at any point in time.
The system should be able to list the transactions that the user has made over time.
The system should prevent the user from withdrawing funds that would leave them with a negative balance, or
 from buying more shares than they can afford, or selling shares that they don't have.
 The system has access to a function get_share_price(symbol) which returns the current price of a share, and includes a test implementation that returns fixed prices for AAPL, TSLA, GOOGL.
"""
# Define the name of the Python module and the main class to be generated.
# These variables are passed to the crew to ensure consistent naming in the generated code.
module_name = "accounts.py"
class_name = "Account"

# --- Main Execution ---
def run():
    """
    Initializes and runs the EngineeringTeam crew.

    This function prepares the inputs and kicks off the crew's process
    to generate the specified software artifacts based on the requirements.
    """
    # Prepare the inputs for the crew kickoff.
    # These values are substituted into the agent and task configurations.
    inputs = {
        'requirements': requirements,
        'module_name': module_name,
        'class_name': class_name
    }

    # Instantiate the EngineeringTeam and execute its crew.
    # The `kickoff` method starts the sequential process defined in the crew,
    # passing the inputs to the agents and tasks.
    result = EngineeringTeam().crew().kickoff(inputs=inputs)


if __name__ == "__main__":
    # This block ensures that the `run` function is called only when the script
    # is executed directly (not when imported as a module).
    run()